---
- name: git clone app
  become_user: root
  git: 
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: "{{ sample_app_dir }}"
    force: yes
  register: git_clone

- name: change owner /var/www/raisetech-live8-sample-app
  become_user: root
  file:
    path: "{{ sample_app_dir }}"
    state: directory
    owner: ec2-user
    recurse: yes
  when: git_clone.changed

- name: create database.yml
  become_user: root
  template:
    src: database.yml.j2
    dest: "{{ sample_app_dir }}/config/database.yml"

- name: create storage.yml
  become_user: root
  template:
    src: storage.yml.j2
    dest: "{{ sample_app_dir }}/config/storage.yml"

- name: Check Unicorn installation
  command: bash -lc "export PATH=/home/ec2-user/.rbenv/shims:$PATH; eval \"$(rbenv init -)\"; gem list --local | grep -iw unicorn"
  register: unicorn_check
  ignore_errors: true

- name: Install Unicorn
  command: bash -lc "export PATH=/home/ec2-user/.rbenv/shims:$PATH; eval \"$(rbenv init -)\"; gem install unicorn"
  when: unicorn_check.stdout == ''

- name: edit development.rb
  become_user: root
  template:
    src: development.rb.j2
    dest: "{{ sample_app_dir }}/config/environments/development.rb"
    
