- name: yum Upgrade all packages
  become: yes
  yum: 
    name: "*"
    state: latest
    update_cache: yes
    skip_broken: yes
  become_user: root

- name: Disable failing repository
  yum:
    name: "*"
    enablerepo: your-failing-repo
    state: disabled

- name: yum install package
  become: yes
  yum:
    state: present
    name: 
      - git
      - make
      - gcc-c++
      - patch
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - libicu-devel
      - libxml2
      - libxslt
      - libxml2-devel
      - libxslt-devel
      
      - zlib-devel
      - readline-devel
      - ImageMagick
      - ImageMagick-devel
