---
- name: Check if Rails is installed
  shell: bash -lc 'rails -v'
  register: rails_check
  ignore_errors: true

- name: Install Rails
  command: bash -lc 'gem install rails'
  when: rails_check.failed
