---
- name: Check Rails version
  command: bash -lc "export PATH=/home/ec2-user/.rbenv/shims:$PATH; eval \"$(rbenv init -)\"; rails -v"
  register: rails_version_check
  ignore_errors: true

- name: Install Rails
  command: bash -lc "export PATH=/home/ec2-user/.rbenv/shims:$PATH; eval \"$(rbenv init -)\"; gem install rails -v 7.1.3.2"
  when: "'Rails 7.1.3.2' not in rails_version_check.stdout"

