---
- name: Initialize rbenv
  lineinfile:
    path: /etc/profile.d/rbenv.sh
    line: 'eval "$(rbenv init -)"'
    create: yes
    state: present

- name: Ensure profile.d scripts are executable
  file:
    path: /etc/profile.d/rbenv.sh
    mode: '0755'
    state: file

- name: Rehash rbenv
  command: bash -lc 'rbenv rehash'
  environment:
    PATH: "/usr/local/rbenv/bin:{{ ansible_env.PATH }}"

- name: Install Rails
  command: bash -lc 'gem install rails -v 7.1.3.2'
  environment:
    PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"

- name: Check Rails version
  command: bash -lc 'rails -v'
  environment:
    PATH: "/usr/local/rbenv/shims:/usr/local/rbenv/bin:{{ ansible_env.PATH }}"
  register: rails_version_check

- debug:
    msg: "Rails version is {{ rails_version_check.stdout }}"
