---
- name: Check if Rails is installed
  shell: bash -lc 'export PATH="/usr/local/rbenv/bin:$PATH"; eval "$(rbenv init -)"; gem list -e rails | grep 7.1.3.2'
  register: rails_check
  changed_when: no
  ignore_errors: true

- name: Install Rails 7.1.3.2
  command: bash -lc 'export PATH="/usr/local/rbenv/bin:$PATH"; eval "$(rbenv init -)"; gem install rails -v 7.1.3.2'
  when: rails_check is failed
