---
- name: Create a swap file
  command: fallocate -l 1G /swapfile
  become: true
  when: ansible_virtualization_type != "lxc"

- name: Set up swap area
  command: mkswap /swapfile
  become: true
  when: ansible_virtualization_type != "lxc"

- name: Enable swap file
  command: swapon /swapfile
  become: true
  when: ansible_virtualization_type != "lxc"

- name: Ensure swap file is enabled at boot
  lineinfile:
    path: /etc/fstab
    line: '/swapfile none swap sw 0 0'
    state: present
  become: true
  when: ansible_virtualization_type != "lxc"

- name: Check Rails version
  command: bash -lc "source ~/.bash_profile && rails -v"
  register: rails_version_check
  ignore_errors: true

- name: Install Rails
  command: bash -lc "source ~/.bash_profile && gem install rails -v 7.1.3.2"
  when: "'Rails 7.1.3.2' not in rails_version_check.stdout"

