---
- hosts: web_server
  remote_user: ec2-user
  tasks:
    - name: dnf Upgrade all packages
      become: yes
      dnf: 
        name: python3-dnf
        state: latest

    - name: dnf install package
      become: yes
      dnf:
        state: present
        name: 
          - git
          - make
          - gcc-c++
          - patch
          - openssl-devel
          - libyaml-devel
          - libffi-devel
          - libicu-devel
          - libxml2
          - libxslt
          - libxml2-devel
          - libxslt-devel
          - zlib-devel
          - readline-devel
          - ImageMagick
          - ImageMagick-devel
