---
- hosts: web_server
  become: yes
  tasks:
    - name: updated yum
      yum:
        name: "*"
        state: latest
      become: yes
    
    - name: installed required packages
      yum:
        name:
          - gcc-c++
          - glibc-headers
          - openssl-devel
          - readline
          - libyaml-devel
          - readline-devel
          - zlib
          - zlib-devel
          - libffi-devel
          - libxml2
          - libxslt
          - libxml2-devel
          - libxslt-devel
          - sqlite-devel
        state: latest
      become: yes

     - name: set LANG=ja_JP.UTF-8 in /etc/locale.conf
      lineinfile:
        dest: /etc/locale.conf
        regexp: "^LANG="
        line: "LANG=ja_JP.UTF-8"
        backup: yes
      become: yes
    
    - name: installed git
      yum:
        name: git
        state: installed
      become: yes
  roles:
    - nginx
