---
- hosts: web_server
  become: yes
  roles:
    - { role: ruby, tags: ruby }
    - { role: bundler, tags: bundler }
    - { role: rails, tags: rails }
    - { role: node, tags: node }
    - { role: yarn, tags: yarn }
    - { role: mysql, tags: mysql }
    
    - { role: nginx, tags: nginx }
    
