---
- hosts: web_server
  become: yes
  tasks:
    - name: updated yum
      yum:
        name: "*"
        state: latest
      become: yes
    
    - name: installed required packages
      yum:
        name:
          - git
          - gcc-c++
          - patch
          - bzip2
          - openssl-devel
          - libyaml-devel
          - libffi-devel
          - readline-devel
          - zlib-devel
          - gdbm-devel
          - ncurses-devel
          - make
          - curl
          - ImageMagick-devel
          - libcurl-devel
          - libicu-devel
          - libxml2-devel
          - libxslt-devel
        state: present
      become: yes

    - name: set LANG=ja_JP.UTF-8 in /etc/locale.conf
      lineinfile:
        dest: /etc/locale.conf
        regexp: "^LANG="
        line: "LANG=ja_JP.UTF-8"
        backup: yes
      become: yes
    
    - name: installed git
      yum:
        name: git
        state: installed
      become: yes

    - name: deployed .bash_profile
      template:
        src: .bash_profile
        dest: ~/.bash_profile
        mode: 0644
      become_user: "{{ __working_user }}"

    - name: made dir .bash.d
      file:
        path: ~/.bash.d
        state: directory
        mode: 0755
      become_user: "{{ __working_user }}"

    - name: installed rbenv
      git:
        repo: https://github.com/sstephenson/rbenv.git
        dest: ~/.rbenv
        

    - name: registerd rbenv path
      template:
        src: ./001_rbenv.sh
        dest: ~/.bash.d/001_rbenv.sh
        mode: 0755
      become_user: "{{ __working_user }}"

    - name: installed ruby-build
      git:
        repo: https://github.com/sstephenson/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build
      become_user: "{{ __working_user }}"
      
