---
- hosts: web_server
  remote_user: ec2-user
  become: yes

  roles:
    - { role: 01_yum, tags: yum }
    - { role: 02_ruby, tags: ruby }
    - { role: 03_bundler, tags: bundler }
    - { role: 04_rails, tags: rails }
    - { role: 05_node, tags: node }
    - { role: 06_yarn, tags: yarn }
    - { role: 07_mysql, tags: mysql }
    - { role: 08_app, tags: app }
    - { role: 09_nginx, tags: nginx }

  vars:
    rbenv_root: "/usr/local/rbenv"
    ruby_version: "3.1.2"
    ansible_become_method: sudo
    sample_app_dir: /var/www/raisetech-live8-sample-app
    aws_alb_host : "{{ (lookup('env','AWS_ALB_HOST')) }}"
    aws_ec2_host : "{{ (lookup('env','AWS_EC2_HOST')) }}"
    aws_db_user: "{{ (lookup('env','AWS_DB_USER')) }}"
    aws_db_pw : "{{ (lookup('env','AWS_DB_PW')) }}"
    aws_db_host : "{{ (lookup('env','AWS_DB_HOST')) }}"
    aws_s3_bucket: "{{ (lookup('env','AWS_S3_BUCKET')) }}"

  tasks:
    - name: Ensure required packages are installed
      yum:
        state: present
        name:
          - git
          - make
          - gcc-c++
          - patch
          - openssl-devel
          - libyaml-devel
          - libffi-devel
          - libicu-devel
          - libxml2
          - libxslt
          - libxml2-devel
          - libxslt-devel
          - zlib-devel
          - readline-devel
          - ImageMagick
          - ImageMagick-devel

    - name: Ensure rbenv is installed
      git:
        repo: 'https://github.com/rbenv/rbenv.git'
        dest: "{{ rbenv_root }}"
        update: no

    - name: Ensure ruby-build is installed
      git:
        repo: 'https://github.com/rbenv/ruby-build.git'
        dest: "{{ rbenv_root }}/plugins/ruby-build"
        update: no

    - name: Add rbenv to PATH and initialize in .bashrc
      lineinfile:
        path: /home/ec2-user/.bashrc
        line: |
          export RBENV_ROOT="{{ rbenv_root }}"
          export PATH="{{ rbenv_root }}/bin:$PATH"
          eval "$(rbenv init -)"
        create: yes
        state: present

    - name: Apply rbenv settings to current shell
      shell: |
        export RBENV_ROOT="{{ rbenv_root }}"
        export PATH="{{ rbenv_root }}/bin:$PATH"
        eval "$(rbenv init -)"

    - name: Install Ruby
      shell: |
        export RBENV_ROOT="{{ rbenv_root }}"
        export PATH="{{ rbenv_root }}/bin:$PATH"
        eval "$(rbenv init -)"
        rbenv install -s {{ ruby_version }}
        rbenv global {{ ruby_version }}
      environment:
        RBENV_ROOT: "{{ rbenv_root }}"
      args:
        executable: /bin/bash

    - name: Install Bundler
      shell: |
        export RBENV_ROOT="{{ rbenv_root }}"
        export PATH="{{ rbenv_root }}/bin:$PATH"
        eval "$(rbenv init -)"
        gem install bundler
      environment:
        RBENV_ROOT: "{{ rbenv_root }}"
      args:
        executable: /bin/bash
