---
- hosts: web_server
  remote_user: ec2-user

  vars: 
    app_dir: /var/www/raisetech-live8-sample-app
    AWS_ALB_DNS_NAME: "{{ lookup('env','AWS_ALB_DNS_NAME') }}"
    AWS_RDS_PW: "{{ lookup('env', 'AWS_RDS_PW') }}"
    AWS_RDS_ENDPOINT: "{{ lookup('env','AWS_RDS_ENDPOINT') }}"
    AWS_S3_BUCKET: "{{ lookup('env','AWS_S3_BUCKET') }}"

  roles:
    - { role: app, tags: app }
