---
- name: Check if bundler is installed
  shell: bash -lc "bundler version | grep {{ bundler_version }}"
  register: bundler_installed
  changed_when: no
  ignore_errors: yes
  environment:
    RBENV_ROOT: /usr/local/rbenv
    PATH: "/usr/local/rbenv/bin:/usr/local/rbenv/shims:{{ ansible_env.PATH }}"

- name: Install bundler
  shell: bash -lc "gem install bundler -v {{ bundler_version }}"
  when: bundler_installed is failed
  environment:
    RBENV_ROOT: /usr/local/rbenv
    PATH: "/usr/local/rbenv/bin:/usr/local/rbenv/shims:{{ ansible_env.PATH }}"
