---
- name: check bundler install
  shell: bash -lc "bundler version | grep {{ bundler_version }}"
  register: bundler_installed
  changed_when: no
  ignore_errors: yes

- name: bundler install
  gem: 
    name: bundler
    version: "{{ bundler_version }}"
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  when: bundler_installed is failed
