---
- name: Check if Bundler is installed
  stat:
    path: /home/ec2-user/.rbenv/versions/3.1.2/bin/bundle
  register: bundler_check

- name: Install Bundler
  command: bash -lc "export PATH=/usr/local/rbenv/shims:$PATH; eval \"$(rbenv init -)\"; gem install bundler 2.3.14"

