---
- name: Check if bundler is installed
  shell: bash -lc "bundler --version"
  register: bundler_installed
  changed_when: false
  ignore_errors: true
  environment:
    RBENV_ROOT: /usr/local/rbenv
    PATH: "/usr/local/rbenv/bin:/usr/local/rbenv/shims:{{ ansible_env.PATH }}"
  failed_when: bundler_installed.rc != 0 or "{{ bundler_version }}" not in bundler_installed.stdout

- name: Install bundler
  shell: bash -lc "gem install bundler -v {{ bundler_version }}"
  when: bundler_installed.failed
  environment:
    RBENV_ROOT: /usr/local/rbenv
    PATH: "/usr/local/rbenv/bin:/usr/local/rbenv/shims:{{ ansible_env.PATH }}"
