---
- name: Install rbenv dependencies
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - gcc
    - make
    - openssl-devel
    - zlib-devel
    - readline-devel

- name: Clone rbenv repository
  become: true
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /usr/local/rbenv
    update: no
  register: rbenv_clone_result

- name: Set RBENV_ROOT environment variable
  become: true
  shell: |
    echo 'export RBENV_ROOT="/usr/local/rbenv"' >> /etc/profile.d/rbenv.sh
    export PATH="$HOME/.rbenv/bin:$PATH"
  args:
    creates: /etc/profile.d/rbenv.sh

- name: Add rbenv to the PATH
  become: true
  shell: |
    echo 'export PATH="$RBENV_ROOT/bin:$PATH"' >> /etc/profile.d/rbenv.sh
  args:
    creates: /etc/profile.d/rbenv.sh

- name: Initialize rbenv
  become: true
  shell: |
    echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh
  args:
    creates: /etc/profile.d/rbenv.sh

- name: Install ruby-build plugin
  become: true
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /usr/local/rbenv/plugins/ruby-build
    update: no

- name: Install Ruby
  become: true
  shell: /usr/local/rbenv/bin/rbenv install 3.1.2
  environment:
    RBENV_ROOT: /usr/local/rbenv
  args:
    creates: /usr/local/rbenv/versions/3.1.2

- name: Set global Ruby version
  become: true
  shell: /usr/local/rbenv/bin/rbenv global 3.1.2
  environment:
    RBENV_ROOT: /usr/local/rbenv
