---
# rbenv------------------------------------------------------------
- name: check rbenv install
  shell: bash -lc "rbenv --version"
  register: check_rbenv_installed
  changed_when: no
  ignore_errors: yes

- name: Install rbenv
  become: yes
  package:
    name: rbenv
    state: present

- name: Configure rbenv
  become: yes
  lineinfile:
    path: /root/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: check_rbenv_installed.failed

- name: eval rbenv init
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
  when: check_rbenv_installed.failed

- name: load .bash_profile
  shell: bash -lc "source ~/.bash_profile"
  when: check_rbenv_installed.failed

# ruby------------------------------------------------------------
- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: check_rbenv_installed.failed

- name: Install Ruby
  become: yes
  shell: rbenv install 3.1.2

- name: rehash rbenv
  shell: bash -lc "rbenv rehash"
  when: check_rbenv_installed.failed

- name: set default ruby version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: check_rbenv_installed.failed
  
