---
# rbenv------------------------------------------------------------
- name: check rbenv install
  shell: bash -lc "rbenv --version"
  register: check_rbenv_installed
  changed_when: no
  ignore_errors: yes

- name: Install rbenv and plugins
  shell: |
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
  args:
    executable: /bin/bash

- name: Install a specific Ruby version
  become: true
  shell: |
    source ~/.bash_profile
    rbenv install 3.1.2
  args:
    executable: /bin/bash

- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: check_rbenv_installed.failed

- name: eval rbenv init
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
  when: check_rbenv_installed.failed

- name: load .bash_profile
  shell: bash -lc "source ~/.bash_profile"
  when: check_rbenv_installed.failed

# ruby------------------------------------------------------------
- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: check_rbenv_installed.failed

- name: install ruby
  shell: bash -lc "rbenv install {{ ruby_version }}"
  when: check_rbenv_installed.failed

- name: rehash rbenv
  shell: bash -lc "rbenv rehash"
  when: check_rbenv_installed.failed

- name: set default ruby version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: check_rbenv_installed.failed
  
