---
# rbenv------------------------------------------------------------
- name: Check rbenv installation
  shell: bash -lc "rbenv --version"
  register: check_rbenv_installed
  changed_when: no
  ignore_errors: yes

- name: Install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: check_rbenv_installed.failed

- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: yes
  when: check_rbenv_installed.failed

- name: Eval rbenv init
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    create: yes
  when: check_rbenv_installed.failed

- name: Load .bash_profile
  shell: bash -lc "source ~/.bash_profile"
  when: check_rbenv_installed.failed

# ruby------------------------------------------------------------
- name: Install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: check_rbenv_installed.failed

- name: Install Ruby
  shell: bash -lc "rbenv install {{ ruby_version }}"
  when: check_rbenv_installed.failed

- name: Rehash rbenv
  shell: bash -lc "rbenv rehash"
  when: check_rbenv_installed.failed

- name: Set default Ruby version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: check_rbenv_installed.failed
