---
- name: Install rbenv dependencies
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - gcc
    - make
    - openssl-devel
    - zlib-devel
    - readline-devel

- name: Clone rbenv repository
  become: true
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /usr/local/rbenv
    update: no
  register: rbenv_clone_result

- name: Set RBENV_ROOT environment variable
  become: true
  shell:
    cmd: echo 'export RBENV_ROOT="/usr/local/rbenv"' >> $HOME/.bash_profile
    creates: $HOME/.bash_profile

- name: Add rbenv to the PATH
  become: true
  shell:
    cmd: echo 'export PATH="$RBENV_ROOT/bin:$PATH"' >> $HOME/.bash_profile
    creates: $HOME/.bash_profile

- name: Install rbenv
      become: yes
      package:
        name: rbenv
        state: present

- name: Initialize rbenv
  become: true
  shell:
    cmd: echo 'eval "$(rbenv init -)"' >> $HOME/.bash_profile
    creates: $HOME/.bash_profile

- name: Install ruby-build plugin
  become: true
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ rbenv_clone_result.changed | ternary('/usr/local/rbenv/plugins/ruby-build', '/usr/local/rbenv/plugins/ruby-build') }}"
    update: no

- name: Install Ruby
  become: true
  shell:
    cmd: rbenv install 3.1.2
